---
title: "0.1_functions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("PAS_design.R")
source("PAS_results.R")
source("results_merged.R")
```

```{r PAS_design}

#this function created  an dds object 
PAS_design<-function(x, PAS, anno){
  dds<-DESeqDataSetFromMatrix(countData = PAS, 
                              colData = anno, 
                              design = x)
  keep<-rowSums(counts(dds)) >=10
  dds<-dds[keep,]
}

x <- ~ Grav + Para + sectio + Csec + place

dds<-PAS_design( x, PAS, anno )
```


```{r}
PAS_results <- function(dds, name, contrast){
    dds <- DESeq(dds)
results <- results(dds, name = name)
results <- results(dds, filterFun= ihw, contrast = contrast)
results <- as.data.frame(results)
results <- results[order(results$padj),]
sig.res<-results|>  #just the sign
  subset(padj<0.05) 
return (sig.res)
}

#objects for the function 
name= "place_PAS_vs_ctrl"
contrast = c("place", "PAS", "ctrl")

#testing function
res<-PAS_results(dds, name, contrast)

#creating a for loop 
PAS_ctrl<-c("place", "PAS", "ctrl")
mus_ctrl<- c("place", "mus", "ctrl")
contrast<- list(PAS_ctrl, mus_ctrl)

# a for loop to loop ovef the list of contrast

res<-list()
for (i in 1:length(contrast)) {
  res[[i]]<- PAS_results(dds, name, contrast[[i]])
  
} 
str(res)
```


```{r}
# merging the results with the gene_id
results_merge<- function(res, PASbackup = PASbackup){
  results_merged<- list()
  
  for (i in 1:length(res)) {
  results_merged[[i]] <- merge(as.data.frame(res[[i]]), 
                               PASbackup, 
                               by.y="gene_id", 
                               by.x= "row.names")
 }
  return(results_merged)
}

ENS<-results_merge(res, PASbackup = PASbackup)

```
# GO with pcaExplore in function 

```{r}
# you take the ENS (merged results)


for (i in 1:length(ENS)){
  ENS[[i]]$Row.names<-gsub("\\..*","", ENS[[i]]$Row.names)
  rownames(ENS[[i]])<-make.names(ENS[[i]]$Row.names, unique=T)
  return(ENS[[i]])
}

results<-ENS[[1]]
PAS_GOexplore<-function(results, dds) {
    genenames_GO<-mapIds(org.Hs.eg.db,
                     keys=results$Row.names, 
                     column = "SYMBOL",
                     keytype = "ENSEMBL")
     annotation_GO <- data.frame(gene_name = genenames_GO,  
                                row.names = row.names(results),
                                stringsAsFactors = FALSE)
     
     res_o <- as.data.frame(results[order(results$padj),])
     de_df <- res_o[res_o$padj < .05 & !is.na(res_o$padj),]
     de_symbols <- de_df$symbol
     bg_ids <- rownames(dds)[rowSums(counts(dds)) > 0]
     bg_ids <- gsub("\\..*","",bg_ids)
     bg_symbols <- mapIds(org.Hs.eg.db,
                     keys=bg_ids,
                     column="SYMBOL",
                     keytype="ENSEMBL",
                     multiVals="first")
     results$symbol<- mapIds(org.Hs.eg.db,
                            keys= row.names(results),
                            column="SYMBOL",
                            keytype="ENSEMBL",
                            multiVals="first")
     results$entrez <- mapIds(org.Hs.eg.db, ##problem 
                            keys=row.names(results), #these keys are not correct
                            column="ENTREZID",
                            keytype="ENSEMBL",
                            multiVals="first")
     topgoDE_GO <- topGOtable(de_symbols, bg_symbols,
                             ontology = "BP",
                             mapping = "org.Hs.eg.db",
                             geneID = "symbol")
     return(topgoDE_GO)
}


PAS_GOexplore(ENS[[1]], dds) #error
```

