---
title: "7.0_visualisation"
output: pdf_document
author: Tina Gorsek Sparovec
date: 24.2.22
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("pasilla")
library("DESeq2")
library("tidyverse")
library("IHW")
library("pheatmap")
library("genefilter")
library("RColorBrewer")
BiocManager::install("vsn")
library("vsn")
library(ggrepel)
```

```{r normalisation}
vsd <- vst(dds, blind=FALSE)
rld <- rlog(dds, blind=FALSE)
ntd <- normTransform(dds)
```

```{r}
sampleDists <- dist(t(assay(vsd)))

sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- paste(vsd$place, vsd$seq_ID, sep="-")
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Reds")) )(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists,
         col=colors)
```

```{r}
topVarGenes <- head(order(-rowVars(assay(rld))),50)

mat <- assay(rld)[ topVarGenes, ]
mat <- mat - rowMeans(mat)
df <- as.data.frame(colData(rld)[,c("place", "patient")])
pheatmap(mat, annotation_col=df)
```

# vulcano plots


```{r}
normalized_counts <- counts(dds, normalized=T) %>% 
                     data.frame() %>%
                     rownames_to_column(var="gene") %>%
                     as_tibble()
# assigning the genes to the column 
summary(results_PAS_ctrl, alpha = 0.05)
# creating a tibble from results 
results_PAS_ctrl2 <- results_PAS_ctrl%>%
   data.frame() %>% 
   rownames_to_column(var="gene")%>%
   as_tibble()
   View()
   
   
results_PAS_ctrl2 <- results_PAS_ctrl2 %>%
  mutate(threshold_OE = padj < 0.05 & abs(log2FoldChange) >= 0.58) %>%
  arrange(padj) %>%
  mutate(genelabels="")

ggplot(results_PAS_ctrl2) +
    geom_point(aes(x = log2FoldChange, y = -log10(padj), colour = threshold_OE)) +
    ggtitle("PAS") +
    xlab("log2 fold change") + 
    ylab("-log10 adjusted p-value") +
    #scale_y_continuous(limits = c(0,50)) +
    theme(legend.position = "none",
          plot.title = element_text(size = rel(1.5), hjust = 0.5),
          axis.title = element_text(size = rel(1.25)))  
```




