---
title: "Exploration_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("pasilla")
library("pasilla")
library("DESeq2")
library("tidyverse")

BiocManager::install(c("IHW","pcaExplorer","clusterProfiler","ReactomePA"))
library(IHW)
library(pcaExplorer)
library(clusterProfiler)
library(ReactomePA)

```

##Sorting the metadata

```{r}
  anno<-read.csv("~/PASproject/metadata_PASeq.csv", 
                  sep= ";")

anno<-anno[, c("place", "seq_ID", "patient", "GW", "sectio", "GDM", "Grav", "Para", "weight", "Csec", "PA_score", "Placenta_previa")]
rownames(anno)<-anno$seq_ID
head(anno)

anno$place<-as.factor(anno$place)
nameplace<-c(control= "ctrl", control_mus= "mus", PAS= "PAS" )
anno$place<- as.character(nameplace[anno$place])
anno$place<-as.factor(anno$place)

anno$seq_ID<-substr(anno$seq_ID, 6,10)
anno$seq_ID<-as.factor(anno$seq_ID)
anno$GDM<-as.factor(anno$GDM)
anno$Grav<-as.factor(anno$Grav)
anno$Para<-as.factor(anno$Para)

namesec<- c("Prim. Sectio"= "1sec", "Prim. sectio"= "1sec", "Sek. Sectio"= "2sec")
anno$sectio<- as.character(namesec[anno$sectio])
anno$sectio<-as.factor(anno$sectio)

#scaling int
anno$GWscaled<-scale(anno$GW, center=TRUE)
#anno$GWscaled<-as.factor(anno$GWscaled)
anno$SWeight<-scale(anno$weight, center = TRUE)
#anno$patient<-as.factor(anno$patient)
anno$Csec<-as.factor(anno$Csec)
anno$PA_score<-as.factor(anno$PA_score)
anno$Placenta_previa<-as.factor(anno$Placenta_previa)

saveRDS(anno, file= "anno.rds")

PAS<-read.table("~/PASproject/raw_file/PAS_counts.tsv", sep="", header = T)

PASbackup<-PAS
PAS<-PAS[,-2]
names<-make.unique(PAS$gene_id) #making the column name gene_names as rown names
rownames(PAS)<-names
PAS<-PAS[,-1]

# rounding up the PAS counts
PAS<-ceiling(PAS[,])

saveRDS(PAS, file="PAS.rds")
```

## Deseq and DE analysis
```{r}
dds<-DESeqDataSetFromMatrix(countData = PAS,
                            colData=anno,
                            design = ~ Grav + Para + sectio + Csec + place)
keep<-rowSums(counts(dds)) >=10
dds<-dds[keep,]
saveRDS(dds, file="dds_mixeddesign.rds")
```

# running the analysis  
## PAS vs ctrl 
```{r}

dds$place<-factor(dds$place, levels= c("ctrl", "mus", "PAS"))
dds <- DESeq(dds)
results_PAS_ctrl <- results(dds)
results_PAS_ctrl<-results(dds, name="place_PAS_vs_ctrl")
results_PAS_ctrl<-results(dds, filterFun= ihw, contrast = c("place", "PAS", "ctrl"))

results_PAS_ctrl<- as.data.frame(results_PAS_ctrl)
results_PAS_ctrl<-results_PAS_ctrl[order(results_PAS_ctrl$padj),]
sig.res<-results_PAS_ctrl|>  #just the sign
  subset(padj<0.05) 


```
## mus vs. ctrl
```{r}

results_mus_ctrl<-results(dds, filterFun= ihw, contrast = c("place", "mus", "ctrl"))
results_mus_ctrl<- as.data.frame(results_mus_ctrl)
results_mus_ctrl<- results_mus_ctrl %>%
  subset(padj<0.05)
```

## pas vs mus
```{r}
results_mus_PAS<-results(dds, filterFun= ihw, contrast = c("place", "mus", "PAS"))
results_mus_PAS<- as.data.frame(results_mus_PAS)
results_mus_PAS<- results_mus_PAS %>%
  subset(padj<0.05)
```

```{r}
ENS_sig<- merge(as.data.frame(sig.res), PASbackup, by.y="gene_id", by.x= "row.names")
ENS_bg<-merge(as.data.frame(results_mus_ctrl), PASbackup, by.y="gene_id", by.x= "row.names")
```

# normalisation
```{r}
vsd <- vst(dds, blind=FALSE)
rld <- rlog(dds, blind=FALSE)
head(assay(rld), 3)
rld_df<-as.matrix(assay(rld))
#rld_df<-as.data.frame(rld_df)

```

# likelihood test ratio
```{r}
dds_lrt <- DESeq(dds, test="LRT", reduced = ~ 1)
res_LRT <- results(dds_lrt)

# Create a tibble for LRT results
res_LRT_tb <- res_LRT %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>% 
  as_tibble()

# Subset to return genes with padj < 0.05
sigLRT_genes <- res_LRT_tb %>% 
  dplyr::filter(padj < 0.05)

# Get number of significant genes
nrow(sigLRT_genes)

```

#clustering the genes 
```{r}
 #Subset results for faster cluster finding (for classroom demo purposes)
clustering_sig_genes <- sigLRT_genes %>%
  arrange(padj) %>%
  head(n=1000)


# Obtain rlog values for those significant genes
rdl_mat<-assay(rld)
cluster_rlog <- rdl_mat[clustering_sig_genes$gene, ]

#you have to put the anno in factors
anno$place<-as.factor(anno$place)
# determining sets of genes with similar expression patterns across sample groups
# Use the `degPatterns` function from the 'DEGreport' package to show gene clusters across sample groups
library(DEGreport)
clusters <- degPatterns(cluster_rlog, metadata = anno, time = "place", col=NULL ) 
#??? put the gene names in the df
head(clusters$df)
```
```{r}
plotPCA(vsd, intgroup="place", ntop=500)+geom_text(aes(label=name),vjust=2)
#color on 2 levels place and PAscore
```
https://bioconductor.org/packages/release/bioc/manuals/ReactomePA/man/ReactomePA.pdf
## ReactomePA



